apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iuh6a61wq-go 
  janus-idp.io/tekton: iuh6a61wq-go
  backstage.io/kubernetes-id: iuh6a61wq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iuh6a61wq-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml