apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iuh6a61wq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iuh6a61wq-go 
  name: iuh6a61wq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iuh6a61wq-go 
